[theme]
primaryColor = "#37ff1493"           # neon green accent
backgroundColor = "#111111"        # dark background
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"              # white text
font = "sans serif"